First implementation of GitLab Adapter
opendatamesh-initiative/odm-platform-adapter-executor-gitlab pull request #1
Opened 2024-08-05 15:41 UTC by PiroX4256

This is the first release of the GitLab adapter for OpenDataMesh devops module.
Key features:

- implemented configurations through parameter service (add and delete).
- implemented API calls to the executor to start or stop pipelines
- implemented interaction with the GitLab API (both on premise and SaaS).

2024-08-05 16:14 UTC, gabrielefantini requested changes

2024-08-05 16:14 UTC, gabrielefantini commented on pom.xml
> +    <parent>
Questo credo lo puoi togliere

2024-08-05 16:14 UTC, gabrielefantini commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
perchè usi un db? non riesci a salvare tutto il necessario utilizzando il params service?

2024-08-05 16:14 UTC, gabrielefantini commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/clients/GitlabClient.java
> +public class GitlabClient extends ODMClient {
Non utilizzare classi di ODM, elimina praticamente tutte le dipendenze con il progetto.
Idem per le api routes.

2024-08-05 16:14 UTC, gabrielefantini commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/clients/GitlabClient.java
> +        return rest.postForEntity(
La gestione della ResponseEntity, così come delle eventuali eccezioni legate alle richieste, secondo me deve essere affidata al Client, perchè sua responsabilità. Guarda la classe BDClientImpl nella repo dell'observer di Blindata per avere una reference.

2024-08-05 16:14 UTC, gabrielefantini commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/clients/GitlabClient.java
> +        return rest.postForEntity(
Se ti fa comodo, copiati la classe RestUtils, che ti semplifica la gestione delle chiamate, specie se hanno un contenuto paginato.

2024-08-05 16:14 UTC, gabrielefantini commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
Questa la terrei come risorsa ma userei il params service come appoggio per la persistenza dei dati.

2024-08-05 16:14 UTC, gabrielefantini commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +    @Value("${polling.retries}")
Come best practice ti consiglio di fare l'injection di tutti i value all'interno di una o più @configuration e poi utilizzare quella dove serve

2024-08-06 15:03 UTC, PiroX4256 commented on pom.xml
> +    <parent>
Probabilmente c'è un refuso nella segnalazione di gitlab, a quali righe ti riferisci? Se tolgo lo schemalocation mi da errore maven mi sa :/

2024-08-06 15:03 UTC, PiroX4256 commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
Serve per salvare le informazioni sulle run, in questo caso ho preso spunto dall'executor di azure devops, che si salva le info storiche sulle run all'interno

2024-08-06 15:04 UTC, gabrielefantini commented on pom.xml
> +    <parent>
No no intendo la dipendenza verso ODM

2024-08-06 15:05 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
Il problema è che questi non sono parametri, ma dati storici, non so se sia una buona idea schiantarli in un param service (a quel punto immagino come stringhe JSON)

2024-08-06 15:12 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/clients/GitlabClient.java
> +public class GitlabClient extends ODMClient {
Fatto

2024-08-06 15:27 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/clients/GitlabClient.java
> +        return rest.postForEntity(
Ok, ho preso spunto dalla vostra repo!

2024-08-06 15:27 UTC, PiroX4256 commented on pom.xml
> +    <parent>
Quindi il parent?

2024-08-06 16:43 UTC, aliprax reviewed
Ho messo qualche nota veloce, niente di chè. Rimane da capire tema del db e del params che onestamente se usati entrambi ha poco senso lato manutenzione e complica solo le cose. Magari facciamo una chiacchiera.

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
> +@Entity(name = "PielineRun")
Eliminare name sulla entity tra l'altro sbagliato (non serve prende già nome della classe)

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
> +@Table(name = "PIPELINE_RUNS", schema = "ODMEXECUTOR")
Lo schema così è fisso e apre a conflitti se ci sono altri executor che vogliono usare stesso nome. Esternalizzare, mettere un default eventualmente sobvrascrivibile per poter far girare più istanze su uno stesso db.

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
> +    @Id
Come viene generato? se c'è una sequence sotto manca @Identity, meglio esplicitarla

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
> +    @Id
se il task id viene da fuori rende impossibile fare reply meglio chiave interna che identifichi la run. se ci sono business rules esplicitarle nel service.

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/dao/PipelineRun.java
> +    protected String gitlabInstanceUrl;
manca column?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/mappers/GitlabPipelineMapper.java
> +        GitlabPipelineResource gitlabPipelineResource = new GitlabPipelineResource();
a cosa serve questo giro? non basta dire al mapper di mappare params in variables?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/ConfigurationResource.java
> +    @JsonProperty("params")
perchè serve?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/ConfigurationResource.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
a cosa serve? non è impostato l'object mapper correttamente?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/TaskResource.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
va configurato su object mapper anzichè ripetuto ogni volta in tutti gli oggetti

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/TaskResource.java
> +
alcuni campi sono package protect altri private perchè?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/TaskResource.java
> +    @JsonProperty("activityId")
Perchè ogni volta json property? i nomi non cambiano mai, basta la reflection di jackson

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/client/gitlab/GitlabPipelineResource.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
replicata, modificare object mapper

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/client/gitlab/GitlabRunResource.java
> +public class GitlabRunResource {
Se questo rappresenta il body di una post cambiamoli nome per far capire che non è una nostra risorsa: e.g. Request o Response a seconda del caso

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/client/params/ParamResource.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
configurazione duplicata, configurare object mapper

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/client/params/ParamResource.java
> +    @JsonProperty("id")
Json Property che non cambiano rispetto al nome del campo, inutili

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/resources/client/params/ParamResource.java
> +    Long id;
campo package protected perchè?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabConfigService.java
> +    private String clientPrefix;
ma che co'sè client-prefix? l'url? baseUrl? il protocol? 
da quello che ho capito è una namespace per il params service, rendere nome variabile più chiaro

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabConfigService.java
> +
Commento ad alto livello se deve essere usato anche il db perchè avere di mezzo anche il params service?

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +    @Value("${polling.retries}")
ma anche il nome polling sulla radice as esempio odm.executors.gitlab.pipelines-config.polling.retries. Dare cmq una struttura e far capire che configurazione manca. polling potrebbe essere di un altra libreria che aggiungiamo in futuro e da questo nome non capisco che è mia

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +        GitlabPipelineResource pipelineResource = pipelineMapper.toGitlabPipelineResource(
non è di facile lettura sono 60/70 righe di gestione di errori per lo più, dove sfugge cosa fa il metodo. i parametri in ingresso sono anche tanti

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +                Objects.requireNonNull(optGitlabInstance.getBody()).getParamName(),
questi generano un 500 non gestito!

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +                Thread.currentThread().interrupt();
ok il flag ma va rilanciata senza andare avanti

2024-08-06 16:43 UTC, aliprax commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +        while (counter < pollingNumRetries) {
ma a cosa serve il polling su delle get? non sono disponibili subito?

2024-08-06 16:43 UTC, aliprax commented on src/main/resources/application-dev.yml
> +polling:
portare le config su un namespace riconducibile a gitlab executor

2024-08-07 07:44 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/mappers/GitlabPipelineMapper.java
> +        GitlabPipelineResource gitlabPipelineResource = new GitlabPipelineResource();
Ti riferisci al for? In quel caso, serve per dividere chiave e valore su due chiavi diverse (chiave 1: key, chiave 2: value), perchè altrimenti me le mappava direttamente in una sola.

2024-08-07 08:00 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabConfigService.java
> +    private String clientPrefix;
è il nome della variabile pari pari a quello del param service, è una sorta di "id" di verifica per inviarsi configurazioni marcate come secret. è come se fosse una API key.

2024-08-07 08:13 UTC, PiroX4256 commented on src/main/java/org/opendatamesh/platform/up/executor/gitlabci/services/GitlabPipelineService.java
> +        while (counter < pollingNumRetries) {
Qui mi sono rifatto al medesimo meccanismo di polling implementato per Azure Devops, in cui viene controllato periodicamente (ogni polling.interval per un masimo di polling.retries) che abbia terminato l'esecuzione della pipeline attraverso una chiamata API di stato a GitLab.

2024-08-07 09:38 UTC, gabrielefantini commented on pom.xml
> +        <dependency>
@PiroX4256 vanno rimosse anche queste dipendenze

2024-08-07 10:39 UTC, PiroX4256 commented on pom.xml
> +        <dependency>
Quindi devo copiare e incollare tutte le classi dentro al mio progetto? Anche quelle del DPDS parser?

2024-08-07 10:54 UTC, gabrielefantini commented on pom.xml
> +        <dependency>
Dove lo usi il parser?

2024-08-07 15:00 UTC, PiroX4256 commented on pom.xml
> +        <dependency>
In effetti ho verificato, sono riuscito a rimuoverlo. A posto!

2024-08-14 10:23 UTC, gabrielefantini commented on src/main/resources/application-dev.yml
>          default_schema: ODMEXECUTOR
questo va tolto no?

2024-08-14 10:23 UTC, gabrielefantini commented on src/main/resources/application-dev.yml
>      schemas: ODMEXECUTOR
idem qua

2024-08-14 10:28 UTC, gabrielefantini approved these changes

2024-08-14 10:28 UTC, merged